name: Shell Commands 

on: [push]

jobs:
  environment: dbg
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: eCCho "Hello Achim"
      - name: multiline script 
        run: |
           node -v 
           npm -v