name: Shell Commands 

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    # set environment to dbg for detailed wf info, otherwise none
    environment: none
    steps: 
      - name: echo a string
        run: echo "Hello Achim"
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command
        run: |
          import platform
          print
          (platform.processor())
        shell: python
        